# Generated by Django 5.0.4 on 2024-04-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('img', models.FileField(upload_to='image-svc')),
                ('stock', models.IntegerField()),
                ('noVenta', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
