# Generated by Django 5.0.4 on 2024-04-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedores',
            table='principal_proveedores',
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('img', models.FileField(upload_to='image-svc')),
                ('stock', models.IntegerField()),
                ('noVenta', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.proveedores')),
            ],
        ),
    ]
