# Generated by Django 5.0.4 on 2024-04-26 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_proveedores_table_marcas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='marcas',
            table='principal_marcas',
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.FileField(upload_to='image-svc')),
                ('stock', models.IntegerField()),
                ('noVenta', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.marcas')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.proveedores')),
            ],
        ),
    ]
